import { defineConfig } from 'oxlint';

export const config = defineConfig({
  categories: {
    correctness: 'off',
  },
  overrides: [
    {
      files: ['**/*.{ts,tsx}'],
      plugins: ['node', 'unicorn'],
      rules: {
        'node/global-require': 'error',
        'node/no-exports-assign': 'error',
        'node/no-new-require': 'error',
        'node/no-process-env': 'error',
        'unicorn/prefer-dom-node-append': 'error',
        'unicorn/prefer-dom-node-dataset': 'error',
        'unicorn/prefer-dom-node-remove': 'error',
        'unicorn/prefer-dom-node-text-content': 'error',
        'unicorn/prefer-keyboard-event-key': 'error',
        'unicorn/prefer-modern-dom-apis': 'error',
        'unicorn/prefer-node-protocol': 'error',
      },
    },
    {
      files: ['**/*.{ts,tsx}'],
      jsPlugins: [
        {
          name: 'perfectionist',
          specifier: 'eslint-plugin-perfectionist',
        },
      ],
      rules: {
        'perfectionist/sort-array-includes': ['error', { order: 'asc', type: 'natural' }],
        'perfectionist/sort-classes': ['error', { order: 'asc', type: 'natural' }],
        'perfectionist/sort-decorators': ['error', { order: 'asc', type: 'natural' }],
        'perfectionist/sort-enums': ['error', { order: 'asc', type: 'natural' }],
        'perfectionist/sort-export-attributes': ['error', { order: 'asc', type: 'natural' }],
        'perfectionist/sort-exports': ['error', { order: 'asc', type: 'natural' }],
        'perfectionist/sort-heritage-clauses': ['error', { order: 'asc', type: 'natural' }],
        'perfectionist/sort-import-attributes': ['error', { order: 'asc', type: 'natural' }],
        'perfectionist/sort-imports': 'off',
        'perfectionist/sort-interfaces': ['error', { order: 'asc', type: 'natural' }],
        'perfectionist/sort-intersection-types': ['error', { order: 'asc', type: 'natural' }],
        'perfectionist/sort-jsx-props': ['error', { order: 'asc', type: 'natural' }],
        'perfectionist/sort-maps': ['error', { order: 'asc', type: 'natural' }],
        'perfectionist/sort-modules': ['error', { order: 'asc', type: 'natural' }],
        'perfectionist/sort-named-exports': ['error', { order: 'asc', type: 'natural' }],
        'perfectionist/sort-named-imports': ['error', { order: 'asc', type: 'natural' }],
        'perfectionist/sort-object-types': ['error', { order: 'asc', type: 'natural' }],
        'perfectionist/sort-objects': ['error', { order: 'asc', type: 'natural' }],
        'perfectionist/sort-sets': ['error', { order: 'asc', type: 'natural' }],
        'perfectionist/sort-switch-case': ['error', { order: 'asc', type: 'natural' }],
        'perfectionist/sort-union-types': ['error', { order: 'asc', type: 'natural' }],
        'perfectionist/sort-variable-declarations': [
          'error',
          { order: 'asc', type: 'natural' },
        ],
      },
    },
    {
      files: ['**/*.{ts,tsx}'],
      plugins: ['jsdoc', 'node', 'unicorn'],
      rules: {
        'accessor-pairs': 'error',
        'array-callback-return': 'error',
        'arrow-body-style': 'off',
        'block-scoped-var': 'error',
        'capitalized-comments': 'off',
        'class-methods-use-this': 'off',
        complexity: ['error', 30],
        'constructor-super': 'error',
        curly: 'error',
        'default-case': 'off',
        'default-case-last': 'off',
        'default-param-last': 'error',
        eqeqeq: 'error',
        'for-direction': 'error',
        'func-names': ['error', 'never'],
        'func-style': ['error', 'expression'],
        'grouped-accessor-pairs': ['error', 'getBeforeSet'],
        'guard-for-in': 'error',
        'id-length': [
          'error',
          {
            exceptions: ['_', '$', 'a', 'b', 'x', 'y', 'z'],
            min: 2,
          },
        ],
        'import/consistent-type-specifier-style': ['error', 'prefer-inline'],
        'import/default': 'error',
        'import/exports-last': 'off',
        'import/extensions': 'off',
        'import/first': 'error',
        'import/group-exports': 'off',
        'import/max-dependencies': 'off',
        'import/namespace': 'off',
        'import/no-absolute-path': 'error',
        'import/no-amd': 'error',
        'import/no-anonymous-default-export': 'off',
        'import/no-commonjs': 'off',
        'import/no-cycle': 'error',
        'import/no-default-export': 'off',
        'import/no-duplicates': [
          'error',
          {
            considerQueryString: true,
            'prefer-inline': true,
          },
        ],
        'import/no-dynamic-require': 'error',
        'import/no-mutable-exports': 'error',
        'import/no-named-as-default': 'error',
        'import/no-named-as-default-member': 'error',
        'import/no-named-default': 'error',
        'import/no-named-export': 'off',
        'import/no-namespace': 'off',
        'import/no-self-import': 'error',
        'import/no-unassigned-import': 'error',
        'import/no-webpack-loader-syntax': 'error',
        'import/prefer-default-export': 'off',
        'import/unambiguous': 'off',
        'init-declarations': 'off',
        'jsdoc/check-access': 'error',
        'jsdoc/check-property-names': 'error',
        'jsdoc/check-tag-names': 'off',
        'jsdoc/empty-tags': 'error',
        'jsdoc/implements-on-classes': 'error',
        'jsdoc/no-defaults': 'error',
        'jsdoc/require-param': 'off',
        'jsdoc/require-param-description': 'off',
        'jsdoc/require-param-name': 'error',
        'jsdoc/require-param-type': 'off',
        'jsdoc/require-property': 'error',
        'jsdoc/require-property-description': 'error',
        'jsdoc/require-property-name': 'error',
        'jsdoc/require-property-type': 'error',
        'jsdoc/require-returns': 'off',
        'jsdoc/require-returns-description': 'off',
        'jsdoc/require-returns-type': 'off',
        'jsdoc/require-yields': 'off',
        'max-classes-per-file': 'off',
        'max-depth': 'off',
        'max-lines': 'off',
        'max-lines-per-function': 'off',
        'max-nested-callbacks': 'off',
        'max-params': 'off',
        'max-statements': 'off',
        'new-cap': 'off',
        'no-alert': 'error',
        'no-array-constructor': 'error',
        'no-async-promise-executor': 'error',
        'no-await-in-loop': 'off',
        'no-bitwise': 'error',
        'no-caller': 'error',
        'no-case-declarations': 'error',
        'no-class-assign': 'error',
        'no-compare-neg-zero': 'error',
        'no-cond-assign': 'error',
        'no-console': 'error',
        'no-const-assign': 'error',
        'no-constant-condition': 'off',
        'no-constructor-return': 'error',
        'no-continue': 'off',
        'no-control-regex': 'off',
        'no-debugger': 'error',
        'no-delete-var': 'error',
        'no-div-regex': 'error',
        'no-dupe-class-members': 'error',
        'no-dupe-else-if': 'error',
        'no-dupe-keys': 'error',
        'no-duplicate-case': 'error',
        'no-duplicate-imports': 'off',
        'no-else-return': 'off',
        'no-empty': 'error',
        'no-empty-character-class': 'off',
        'no-empty-pattern': 'error',
        'no-eq-null': 'error',
        'no-eval': 'error',
        'no-ex-assign': 'error',
        'no-extend-native': 'error',
        'no-extra-bind': 'error',
        'no-extra-boolean-cast': 'error',
        'no-extra-label': 'error',
        'no-fallthrough': 'off',
        'no-func-assign': 'error',
        'no-global-assign': 'error',
        'no-implicit-coercion': 'error',
        'no-import-assign': 'error',
        'no-inline-comments': 'off',
        'no-inner-declarations': 'error',
        'no-invalid-regexp': 'off',
        'no-irregular-whitespace': 'error',
        'no-iterator': 'error',
        'no-label-var': 'error',
        'no-labels': 'error',
        'no-lone-blocks': 'error',
        'no-lonely-if': 'error',
        'no-loop-func': 'error',
        'no-loss-of-precision': 'error',
        'no-magic-numbers': 'off',
        'no-multi-assign': 'error',
        'no-multi-str': 'error',
        'no-negated-condition': 'error',
        'no-nested-ternary': 'off',
        'no-new': 'error',
        'no-new-func': 'error',
        'no-new-wrappers': 'error',
        'no-nonoctal-decimal-escape': 'error',
        'no-obj-calls': 'error',
        'no-param-reassign': [
          'error',
          {
            props: false,
          },
        ],
        'no-plusplus': 'off',
        'no-promise-executor-return': 'error',
        'no-proto': 'error',
        'no-prototype-builtins': 'error',
        'no-redeclare': [
          'error',
          {
            builtinGlobals: true,
          },
        ],
        'no-regex-spaces': 'error',
        'no-restricted-globals': 'off',
        'no-restricted-imports': 'off',
        'no-return-assign': 'error',
        'no-script-url': 'error',
        'no-self-assign': 'error',
        'no-self-compare': 'error',
        'no-sequences': 'error',
        'no-setter-return': 'error',
        'no-shadow-restricted-names': 'error',
        'no-sparse-arrays': 'error',
        'no-template-curly-in-string': 'error',
        'no-ternary': 'off',
        'no-this-before-super': 'error',
        'no-throw-literal': 'error',
        'no-undefined': 'off',
        'no-unexpected-multiline': 'error',
        'no-unneeded-ternary': 'error',
        'no-unsafe-finally': 'error',
        'no-unsafe-negation': 'error',
        'no-unsafe-optional-chaining': 'error',
        'no-unused-expressions': 'error',
        'no-unused-labels': 'error',
        'no-unused-private-class-members': 'off',
        'no-unused-vars': 'error',
        'no-useless-backreference': 'off',
        'no-useless-call': 'error',
        'no-useless-catch': 'error',
        'no-useless-computed-key': 'error',
        'no-useless-concat': 'error',
        'no-useless-constructor': 'error',
        'no-useless-escape': 'error',
        'no-useless-rename': [
          'error',
          {
            ignoreDestructuring: false,
            ignoreExport: false,
            ignoreImport: false,
          },
        ],
        'no-useless-return': 'error',
        'no-var': 'error',
        'no-void': [
          'error',
          {
            allowAsStatement: true,
          },
        ],
        'no-warning-comments': [
          'warn',
          {
            location: 'start',
            terms: ['todo', '@toto'],
          },
        ],
        'no-with': 'error',
        'operator-assignment': ['error', 'always'],
        'prefer-destructuring': 'off',
        'prefer-exponentiation-operator': 'error',
        'prefer-numeric-literals': 'error',
        'prefer-object-spread': 'error',
        'prefer-promise-reject-errors': 'error',
        'prefer-rest-params': 'error',
        'prefer-spread': 'error',
        'prefer-template': 'off',
        'promise/param-names': 'error',
        'promise/prefer-await-to-callbacks': 'off',
        'promise/prefer-await-to-then': 'error',
        'promise/valid-params': 'error',
        radix: 'error',
        'require-await': 'off',
        'require-yield': 'error',
        'sort-imports': 'off',
        'sort-keys': 'off',
        'sort-vars': 'error',
        'symbol-description': 'error',
        'unicode-bom': ['error', 'never'],
        'unicorn/catch-error-name': [
          'error',
          {
            name: 'error',
          },
        ],
        'unicorn/consistent-function-scoping': [
          'error',
          {
            checkArrowFunctions: false,
          },
        ],
        'unicorn/empty-brace-spaces': 'error',
        'unicorn/error-message': 'error',
        'unicorn/escape-case': 'error',
        'unicorn/explicit-length-check': 'off',
        'unicorn/filename-case': 'off',
        'unicorn/new-for-builtins': 'error',
        'unicorn/no-abusive-oxlint-disable': 'error',
        'unicorn/no-array-callback-reference': 'off',
        'unicorn/no-array-for-each': 'error',
        'unicorn/no-array-method-this-argument': 'error',
        'unicorn/no-array-reduce': [
          'error',
          {
            allowSimpleOperations: true,
          },
        ],
        'unicorn/no-array-reverse': 'error',
        'unicorn/no-array-sort': 'error',
        'unicorn/no-await-expression-member': 'off',
        'unicorn/no-console-spaces': 'off',
        'unicorn/no-document-cookie': 'error',
        'unicorn/no-empty-file': 'error',
        'unicorn/no-hex-escape': 'error',
        'unicorn/no-immediate-mutation': 'off',
        'unicorn/no-instanceof-array': 'error',
        'unicorn/no-invalid-remove-event-listener': 'error',
        'unicorn/no-lonely-if': 'error',
        'unicorn/no-nested-ternary': 'off',
        'unicorn/no-new-array': 'error',
        'unicorn/no-new-buffer': 'error',
        'unicorn/no-null': 'off',
        'unicorn/no-object-as-default-parameter': 'error',
        'unicorn/no-process-exit': 'off',
        'unicorn/no-static-only-class': 'error',
        'unicorn/no-thenable': 'error',
        'unicorn/no-this-assignment': 'error',
        'unicorn/no-unnecessary-array-flat-depth': 'error',
        'unicorn/no-unnecessary-array-splice-count': 'error',
        'unicorn/no-unreadable-array-destructuring': 'off',
        'unicorn/no-unreadable-iife': 'error',
        'unicorn/no-useless-collection-argument': 'error',
        'unicorn/no-useless-error-capture-stack-trace': 'error',
        'unicorn/no-useless-fallback-in-spread': 'error',
        'unicorn/no-useless-length-check': 'error',
        'unicorn/no-useless-promise-resolve-reject': 'error',
        'unicorn/no-useless-spread': 'error',
        'unicorn/no-useless-switch-case': 'off',
        'unicorn/no-useless-undefined': 'off',
        'unicorn/no-zero-fractions': 'error',
        'unicorn/number-literal-case': 'error',
        'unicorn/numeric-separators-style': [
          'error',
          {
            number: {
              groupLength: 3,
              minimumDigits: 0,
            },
          },
        ],
        'unicorn/prefer-add-event-listener': 'off',
        'unicorn/prefer-array-find': 'error',
        'unicorn/prefer-array-flat': 'error',
        'unicorn/prefer-array-flat-map': 'error',
        'unicorn/prefer-array-index-of': 'error',
        'unicorn/prefer-array-some': 'error',
        'unicorn/prefer-at': 'off',
        'unicorn/prefer-bigint-literals': 'error',
        'unicorn/prefer-blob-reading-methods': 'error',
        'unicorn/prefer-class-fields': 'error',
        'unicorn/prefer-classlist-toggle': 'error',
        'unicorn/prefer-code-point': 'error',
        'unicorn/prefer-date-now': 'error',
        'unicorn/prefer-default-parameters': 'error',
        'unicorn/prefer-includes': 'error',
        'unicorn/prefer-math-trunc': 'off',
        'unicorn/prefer-modern-math-apis': 'error',
        'unicorn/prefer-native-coercion-functions': 'error',
        'unicorn/prefer-negative-index': 'off',
        'unicorn/prefer-number-properties': 'error',
        'unicorn/prefer-object-from-entries': 'error',
        'unicorn/prefer-optional-catch-binding': 'error',
        'unicorn/prefer-prototype-methods': 'off',
        'unicorn/prefer-query-selector': 'error',
        'unicorn/prefer-reflect-apply': 'error',
        'unicorn/prefer-regexp-test': 'error',
        'unicorn/prefer-response-static-json': 'error',
        'unicorn/prefer-set-has': 'off',
        'unicorn/prefer-spread': 'off',
        'unicorn/prefer-string-replace-all': 'error',
        'unicorn/prefer-string-slice': 'error',
        'unicorn/prefer-string-starts-ends-with': 'error',
        'unicorn/prefer-string-trim-start-end': 'error',
        'unicorn/prefer-top-level-await': 'off',
        'unicorn/prefer-type-error': 'error',
        'unicorn/require-array-join-separator': 'error',
        'unicorn/require-module-attributes': 'error',
        'unicorn/require-module-specifiers': 'error',
        'unicorn/require-number-to-fixed-digits-argument': 'error',
        'unicorn/require-post-message-target-origin': 'error',
        'unicorn/text-encoding-identifier-case': 'error',
        'unicorn/throw-new-error': 'error',
        'use-isnan': 'error',
        'valid-typeof': [
          'error',
          {
            requireStringLiterals: true,
          },
        ],
        'vars-on-top': 'error',
        yoda: ['error', 'never'],
      },
    },
    {
      files: ['**/*.{ts,tsx}'],
      plugins: ['typescript', 'import', 'jsdoc'],
      rules: {
        '@typescript-eslint/adjacent-overload-signatures': 'error',
        '@typescript-eslint/array-type': [
          'error',
          {
            default: 'array-simple',
          },
        ],
        '@typescript-eslint/ban-ts-comment': [
          'error',
          {
            'ts-check': true,
            'ts-expect-error': 'allow-with-description',
            'ts-ignore': false,
            'ts-nocheck': false,
          },
        ],
        '@typescript-eslint/ban-tslint-comment': 'error',
        '@typescript-eslint/ban-types': 'off',
        '@typescript-eslint/consistent-indexed-object-style': 'off',
        '@typescript-eslint/consistent-type-definitions': ['error', 'type'],
        '@typescript-eslint/consistent-type-imports': [
          'error',
          {
            prefer: 'type-imports',
          },
        ],
        '@typescript-eslint/explicit-function-return-type': 'off',
        '@typescript-eslint/explicit-module-boundary-types': 'off',
        '@typescript-eslint/no-confusing-non-null-assertion': 'error',
        '@typescript-eslint/no-dynamic-delete': 'error',
        '@typescript-eslint/no-empty-interface': [
          'error',
          {
            allowSingleExtends: false,
          },
        ],
        '@typescript-eslint/no-explicit-any': [
          'error',
          {
            ignoreRestArgs: true,
          },
        ],
        '@typescript-eslint/no-extra-non-null-assertion': 'error',
        '@typescript-eslint/no-extraneous-class': 'error',
        '@typescript-eslint/no-inferrable-types': [
          'error',
          {
            ignoreParameters: true,
            ignoreProperties: true,
          },
        ],
        '@typescript-eslint/no-misused-new': 'error',
        '@typescript-eslint/no-namespace': [
          'error',
          {
            allowDeclarations: true,
          },
        ],
        '@typescript-eslint/no-non-null-asserted-nullish-coalescing': 'error',
        '@typescript-eslint/no-non-null-asserted-optional-chain': 'error',
        '@typescript-eslint/no-non-null-assertion': 'error',
        '@typescript-eslint/no-require-imports': 'error',
        '@typescript-eslint/no-this-alias': [
          'error',
          {
            allowDestructuring: true,
            allowedNames: ['self'],
          },
        ],
        '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'off',
        '@typescript-eslint/no-unnecessary-type-arguments': 'off',
        '@typescript-eslint/no-unnecessary-type-assertion': 'off',
        '@typescript-eslint/no-unnecessary-type-constraint': 'error',
        '@typescript-eslint/no-unsafe-argument': 'off',
        '@typescript-eslint/no-unsafe-assignment': 'off',
        '@typescript-eslint/no-unsafe-call': 'off',
        '@typescript-eslint/no-unsafe-member-access': 'off',
        '@typescript-eslint/no-unsafe-return': 'off',
        '@typescript-eslint/no-var-requires': 'error',
        '@typescript-eslint/non-nullable-type-assertion-style': 'off',
        '@typescript-eslint/prefer-as-const': 'error',
        '@typescript-eslint/prefer-enum-initializers': 'error',
        '@typescript-eslint/prefer-for-of': 'error',
        '@typescript-eslint/prefer-function-type': 'error',
        '@typescript-eslint/prefer-literal-enum-member': 'error',
        '@typescript-eslint/prefer-namespace-keyword': 'error',
        '@typescript-eslint/prefer-ts-expect-error': 'error',
        '@typescript-eslint/require-await': 'off',
        '@typescript-eslint/restrict-plus-operands': 'off',
        '@typescript-eslint/restrict-template-expressions': 'off',
        '@typescript-eslint/strict-boolean-expressions': 'off',
        '@typescript-eslint/triple-slash-reference': [
          'error',
          {
            lib: 'never',
            path: 'never',
            types: 'never',
          },
        ],
        'default-param-last': 'error',
        'import/no-dynamic-require': 'off',
        'init-declarations': 'off',
        'jsdoc/require-property-type': 'off',
        'no-array-constructor': 'error',
        'no-dupe-class-members': 'error',
        'no-duplicate-imports': 'off',
        'no-empty-function': 'off',
        'no-loop-func': 'error',
        'no-loss-of-precision': 'error',
        'no-magic-numbers': 'off',
        'no-redeclare': [
          'error',
          {
            builtinGlobals: true,
          },
        ],
        'no-restricted-imports': 'off',
        'no-throw-literal': 'off',
        'no-unused-expressions': [
          'error',
          {
            allowShortCircuit: false,
            allowTaggedTemplates: false,
            allowTernary: false,
            enforceForJSX: false,
          },
        ],
        'no-unused-vars': 'error',
        'no-useless-constructor': 'error',
        'node/global-require': 'off',
        'require-await': 'off',
      },
    },
    {
      files: ['**/*.{jsx,tsx}'],
      globals: {
        AudioWorkletGlobalScope: 'readonly',
        AudioWorkletProcessor: 'readonly',
        currentFrame: 'readonly',
        currentTime: 'readonly',
        registerProcessor: 'readonly',
        sampleRate: 'readonly',
        WorkletGlobalScope: 'readonly',
      },
      plugins: ['react'],
      rules: {
        'react/button-has-type': 'error',
        'react/display-name': 'off',
        'react/forbid-dom-props': 'off',
        'react/forbid-elements': 'off',
        'react/iframe-missing-sandbox': 'error',
        'react/jsx-boolean-value': ['error', 'never'],
        'react/jsx-curly-brace-presence': [
          'error',
          {
            children: 'never',
            props: 'never',
          },
        ],
        'react/jsx-filename-extension': 'off',
        'react/jsx-fragments': ['error', 'syntax'],
        'react/jsx-handler-names': [
          'error',
          {
            checkInlineFunction: false,
            checkLocalVariables: false,
            eventHandlerPrefix: 'handle',
            eventHandlerPropPrefix: 'on',
          },
        ],
        'react/jsx-key': [
          'error',
          {
            checkFragmentShorthand: true,
            checkKeyMustBeforeSpread: true,
          },
        ],
        'react/jsx-max-depth': 'off',
        'react/jsx-no-comment-textnodes': 'error',
        'react/jsx-no-duplicate-props': 'error',
        'react/jsx-no-script-url': 'error',
        'react/jsx-no-target-blank': 'error',
        'react/jsx-no-undef': 'error',
        'react/jsx-no-useless-fragment': [
          'error',
          {
            allowExpressions: true,
          },
        ],
        'react/jsx-pascal-case': [
          'error',
          {
            ignore: [
              'h{}',
              'h2',
              'h3',
              'h4',
              'h5',
              'h6',
              'p',
              'a',
              'ul',
              'ol',
              'li',
              'img',
              'div',
              'span',
              'dl',
              'dt',
              'dd',
            ],
          },
        ],
        'react/jsx-props-no-spreading': 'off',
        'react/no-array-index-key': 'error',
        'react/no-children-prop': 'error',
        'react/no-danger': 'error',
        'react/no-danger-with-children': 'error',
        'react/no-did-mount-set-state': 'error',
        'react/no-direct-mutation-state': 'error',
        'react/no-find-dom-node': 'error',
        'react/no-is-mounted': 'error',
        'react/no-namespace': 'error',
        'react/no-redundant-should-component-update': 'error',
        'react/no-render-return-value': 'error',
        'react/no-set-state': 'error',
        'react/no-string-refs': 'error',
        'react/no-this-in-sfc': 'error',
        'react/no-unescaped-entities': 'off',
        'react/no-unknown-property': 'error',
        'react/no-unsafe': 'error',
        'react/no-will-update-set-state': 'error',
        'react/prefer-es6-class': 'error',
        'react/react-in-jsx-scope': 'off',
        'react/self-closing-comp': 'error',
        'react/state-in-constructor': ['error', 'always'],
        'react/style-prop-object': 'error',
        'react/void-dom-elements-no-children': 'error',
      },
    },
    {
      files: ['**/*.{js,jsx,ts,tsx}'],
      plugins: ['react'],
      rules: {
        'react-hooks/exhaustive-deps': 'error',
        'react-hooks/rules-of-hooks': 'error',
      },
    },
  ],
});